### ISSUE TITLE
Support UE5.1

### ISSUE THREAD

**Issue by colinbouvry** [AskingQuestions/Shadeup#1]
Hello
I believe that [ComputeShader_rt.zip](https://github.com/AskingQuestions/Shadeup/blob/main/archives/ComputeShader_rt.zip) does not work without some issues.

**Comment by AskingQuestions** [comment]
Hey, thanks for the report!

I've just pushed a release (8629bd8) which should address the issues you're running into on 5.1.

Feel free to pull down the latest archive from the repo or download from the [site](https://shadeup.dev/docs/compute/rt) and let me know if it's working for you. Thanks

Example of the Compute Shader RT build running in 5.1:

![snip](https://user-images.githubusercontent.com/18402381/205455006-51167476-356b-439d-b26e-addfbd108fd1.png)

**Comment by colinbouvry** [comment]
Thanks and congrat !
RT works now. 
How do you do to refresh shader ExampleComputeShader.usf without relaunch UE ?
With ComputeShader_mat I have this error :
![image](https://user-images.githubusercontent.com/985676/205459910-44ed6849-9dfb-4910-b4da-f959f27e829f.png)

**Comment by AskingQuestions** [comment]
`Ctrl` + `Shift` + `.` will recompile shaders. That should update your compute shader as you make changes

**Comment by colinbouvry** [comment]
enable r.ShaderDevelopmentMode by setting it to 1
I change the .usf file in visual studio and Ctrl + Shift + . for recompile shaders and nothing change.
I just change RenderTarget[DispatchThreadId.xy] = float3(1.0, 0.0, 0.0); to test
Any idea ?

**Comment by AskingQuestions** [comment]
Hmm, was it rendering the checkerboard previously? Also, are you using the plain compute shader to render target example or the material to render target one?

If you're using the material to render target example please make sure the `Use with virtual heightfield mesh` is checked off in the material editor for the material you're using:

![image](https://user-images.githubusercontent.com/18402381/205461980-e72d3ce1-968d-4385-9cb4-8398e81e0ff5.png)

**Comment by colinbouvry** [comment]
It rendering the checkerboard previously.
I use ComputeShader_rt.
I'm using the plain compute shader to render target and material with render target inside
![image](https://user-images.githubusercontent.com/985676/205462376-40227fce-f8f1-402a-bb2c-30316d904afa.png)
![image](https://user-images.githubusercontent.com/985676/205462568-c54b2c6c-f896-41a5-b164-6f25597b83d7.png)

**Comment by colinbouvry** [comment]
I still can't update the new shader !
Is it possible to add usf into UE5 ?

**Comment by AskingQuestions** [comment]
Can you paste this into the usf file just as a sanity check and then restart the editor:

```hlsl
#include "/Engine/Public/Platform.ush"

RWTexture2D<float3> RenderTarget;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MySimpleComputeShader(
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint GroupIndex : SV_GroupIndex )
{
	// Simple checkerboard
	int x = floor(DispatchThreadId.x / 16.f);
	int y = floor(DispatchThreadId.y / 16.f);
	int c = (x + y % 2) % 2;
	
	RenderTarget[DispatchThreadId.xy] = float3(1.0, 0.0, 0.0);
}
```

**Comment by AskingQuestions** [comment]
Are you getting the 
![image](https://user-images.githubusercontent.com/18402381/205463604-7d53be3b-0aa7-47e8-9dca-9ede2c5aebaa.png)
error still?

**Comment by colinbouvry** [comment]
I check usf and relaunch I have well the red color.
I have always the problem to refresh shader !
Any idea ?

**Comment by AskingQuestions** [comment]
The only thing I can think of would be to add `r.ShaderDevelopmentMode 1` to your ConsoleVariables.ini as per the [ue guide](https://docs.unrealengine.com/4.26/en-US/ProgrammingAndScripting/Rendering/ShaderDevelopment/)

>When working on shaders, be sure to enable r.ShaderDevelopmentMode by setting it to 1. The easiest way is to edit ConsoleVariables.ini so it is done every time you load. This will enable retry-on-error and shader development related logs and warnings.

Could there be any macro or external keyboard thing that's intercepting the Ctrl Shift . shortcut?

**Comment by colinbouvry** [comment]
I add r.ShaderDevelopmentMode 1 to my ConsoleVariables.in
I have a popup when I tape  Ctrl Shift . but I think It is always at 100% no change detected.
It's the same !

**Comment by colinbouvry** [comment]
I type this command 
> recompileshaders changed
[2022.12.04-00.27.56:440][129]LogShaders: Shader directory mapping /ComputeShaderShaders -> ../../../../../../dev/UnrealProjects/CCA/Plugins/ComputeShader_Plugin/Shaders/ComputeShader/Private
[2022.12.04-00.27.57:431][129]LogShaderCompilers: Warning: 		[Searching for changed files] took [0.5761] s
[2022.12.04-00.27.57:432][129]LogShaderCompilers: Warning: No Shader changes found.

**Comment by colinbouvry** [comment]
It works now ! 
I added several lines and now it works with this command recompileshaders changed

**Comment by AskingQuestions** [comment]
Ah, glad to hear it, and happy to help!
