### ISSUE TITLE
Cannot run "Bare-bones material graph evaluation" example

### ISSUE THREAD

**Issue by oktomus** [AskingQuestions/Shadeup#4]
Hi! First of all, thanks for making Shadeup, it's a really cool and useful website :)

I am not able to run the [Bare-bones material graph evaluation](https://shadeup.dev/docs/compute/basemat) example, there is some problems with the compute shader.

![image](https://user-images.githubusercontent.com/4656466/213506034-b4b24312-ccfe-43aa-b161-40ac098dab3a.png)

The problem happens on 5.0 and 5.1.

After recompiling shaders (CTRL + SHIFT + I or with the command `recompileshaders changed`), I noticed the shader of that example was never in the list, even if I edit it. With `r.DumpShaderDebugInfo = 1`, I noticed the shader was not even in the cache:
![image](https://user-images.githubusercontent.com/4656466/213507862-42ac73d2-8e96-477f-8181-0447f8abf96d.png)
![image](https://user-images.githubusercontent.com/4656466/213508047-2c4d8e81-df36-4f8d-a5dc-666fa8fcb7b4.png)

Here is the BP I run when playing the game:
![image](https://user-images.githubusercontent.com/4656466/213505875-8885f679-1c4a-4a8e-bb5c-4b5696dc27ad.png)

The material used as input of the CS:
![image](https://user-images.githubusercontent.com/4656466/213505953-cf4f7cd1-e594-4ca9-a174-b4061a6c4237.png)

**Comment by oktomus** [comment]
On the other hand, the CalculatePI example works perfectly

**Comment by AskingQuestions** [comment]
Thanks for the detailed report!

This is something that I neglected to mention in the docs but please make sure the material has the following:
1. Material domain of `Surface `
2. Blend mode of `Opaque`
3. Shading model of `DefaultLit`
4. `Used With Virtual HeightfieldMesh` checked off in the details panel

After that please click apply, if there are any errors please screenshot and share here (they should show up in the output panel)

![image](https://user-images.githubusercontent.com/18402381/213512097-8b00b4e0-8161-4d87-9eb1-89fa910574df.png)
![image](https://user-images.githubusercontent.com/18402381/213512315-a47ff5b9-0a79-4d99-a90e-65bedd2f5e60.png)

**Comment by oktomus** [comment]
Hi,

I still have the same problem 
![image](https://user-images.githubusercontent.com/4656466/213657580-e59a2614-b64a-429a-a908-77b7aec1d8fb.png)

So I tried to do exactly as you, meaning having a Material variable, and now it works.
![image](https://user-images.githubusercontent.com/4656466/213657728-4fdfc263-a110-4fac-8f2f-c55c35e0cc93.png)
![image](https://user-images.githubusercontent.com/4656466/213657776-42d4e371-9956-45e0-9e73-6d6c05eb4306.png)

It's super weird no?

**Comment by oktomus** [comment]
It crashes when using these nodes, I guess something is missing on the compute shader side to bind these values right ? 
![image](https://user-images.githubusercontent.com/4656466/213662212-520df0f9-3722-46f8-b113-b436d3e48ed2.png)

**Comment by AskingQuestions** [comment]
> It's super weird no?

Yeah, that's strange. Maybe there's a compilation error somewhere that got resolved with that swap.

> It crashes when using these nodes, I guess something is missing on the compute shader side to bind these values right ?

Yeah, I suspect that something in the global view uniform buffer is missing. There's a spot in the main ComputeShader.cpp file that looks like this:

```cpp
FViewUniformShaderParameters ViewUniformShaderParameters;

ViewUniformShaderParameters.GameTime = GameTime;
ViewUniformShaderParameters.Random = Random;
```

I'd take a look at what values that bounding box node uses and try to get those filled in the `FViewUniformShaderParameters` struct
