### ISSUE TITLE
[Base Computer Shader]: Output is always 0 in UE5.1.1

### ISSUE THREAD

**Issue by roadstargames** [AskingQuestions/Shadeup#7]
Thank you for your great examples!

But I alway get 0 on output. Even when change the output to: 

`Output[0] = Input[0];`

This is my 5.1.1 default Third Person test project with plugin if you would to try by yourself (just build the binaries).

https://www.dropbox.com/s/ya9makoru5dfua8/CompShader51.zip?dl=0

Thank you in advance!
Vlad

**Comment by AskingQuestions** [comment]
Thanks for the report and repro.

Looks like the print wire needs to be hooked up to the completed event.

![image](https://user-images.githubusercontent.com/18402381/222537872-3895f839-6326-4de9-b4f9-04ec1956ef04.png)

It's an async operation so the results are not ready until a frame or so later.

Let me know if that fixes it

**Comment by roadstargames** [comment]
Oh, man!
I've tried but forgot it's working in Runtime only - not in Editor.
Thank you once again for such fast response and for your great learning resource!
Cheers!
Vlad
