### ISSUE TITLE
Pass Buffer<float4> into compute shader

### ISSUE THREAD

**Issue by Zifkan** [AskingQuestions/Shadeup#8]
Hello im on UE 5.3. I need some help with passing data into like this.  Params.CameraPlanes this is  TArray<FVector4>.
![image](https://user-images.githubusercontent.com/7218326/228051012-011bef5e-7040-425c-94b6-32ff678ebd8d.png)

Declaration buffer look like this 
![image](https://user-images.githubusercontent.com/7218326/228051390-6ed2290a-19f4-4845-9208-74a4c2f665f5.png)

And in Compute shader
![image](https://user-images.githubusercontent.com/7218326/228051494-5d9940f3-3bb8-48ee-bf3d-002931d3f2f5.png)

So problem that data passed incorrect.  Im not sure about using PF_FloatRGBA in GraphBuilder.CreateSRV. I also tried PF_A32B32G32R32F. So tips about this param will be welcome 
Thank you for any tips

**Comment by kristiamo** [comment]
> First way worked fine, but 2nd still not.

To add onto the answer you already got: I had a similar frustrating issue before I remembered UE internally uses doubles (FVector4 = FVector4d, not FVector4f).  I'm assuming Params.CameraPlanes.GetData() is pointing to a TArray<FVector4>.  So you were taking an array of 4 doubles, and telling the shader to interpret 4floats.

Your 2 options would be to convert your input Params.CameraPlanes (dispatch params) to a TArray<FVector4f> first
OR go back to FVector4 everywhere but change all the shader buffers to Buffer<double4>

**Comment by kristiamo** [comment]
> First way worked fine, but 2nd still not.

To add onto the answer you already got: I had a similar frustrating issue before I remembered UE internally uses doubles (FVector4 = FVector4d, not FVector4f).  I'm assuming `Params.CameraPlanes.GetData()` is pointing to a `TArray<FVector4>`.  So you were taking an array of 4 doubles, and telling the shader to interpret 4floats.

Your 2 options would be to convert your input Params.CameraPlanes (dispatch params) to a `TArray<FVector4f>` first
OR go back to FVector4 everywhere but change all the shader buffers to `Buffer<double4>`

**Comment by Zifkan** [comment]
> > First way worked fine, but 2nd still not.
> 
> To add onto the answer you already got: I had a similar frustrating issue before I remembered UE internally uses doubles (FVector4 = FVector4d, not FVector4f). I'm assuming `Params.CameraPlanes.GetData()` is pointing to a `TArray<FVector4>`. So you were taking an array of 4 doubles, and telling the shader to interpret 4floats.
> 
> Your 2 options would be to convert your input Params.CameraPlanes (dispatch params) to a `TArray<FVector4f>` first OR go back to FVector4 everywhere but change all the shader buffers to `Buffer<double4>`

ty for reply i already solve this problem
